# NumPy 

[NumPy](https://docs.scipy.org/doc/numpy/user/quickstart.html) é uma biblioteca python para operações de algebra linear. É uma ferramenta poderosa e importante no âmbito da ciência de dados devido às suas funcionalidades e por servir de ferramenta base para a construções de várias outras bibliotecas.

## Vamos importar

In [1]:
import numpy as np

# Numpy Arrays

### Criando numpy arrays a partir de listas

In [4]:
lista = [1,2,3] #lista em python
lista

[1, 2, 3]

In [5]:
np.array(lista) # um numpy array

array([1, 2, 3])

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(matrix) # uma matriz numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Métodos

### arange

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## eye
matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Criando arrays randômicos

### rand

In [15]:
np.random.rand(2)

array([0.63828542, 0.21014494])

In [16]:
np.random.rand(5,5)

array([[0.44646302, 0.01710812, 0.6769573 , 0.89973244, 0.32746992],
       [0.38369593, 0.24162955, 0.55460617, 0.52135485, 0.61729866],
       [0.70450936, 0.5284597 , 0.28813515, 0.75921068, 0.23809012],
       [0.45435426, 0.42454301, 0.57196491, 0.11932069, 0.00361814],
       [0.23227229, 0.80131517, 0.72145773, 0.47461393, 0.51722479]])

### randn

In [17]:
np.random.randn(2)

array([-0.27054274,  0.86942038])

In [18]:
np.random.randn(5,5)

array([[-1.88834423,  2.23359032, -0.86708161,  0.39479635,  0.30144742],
       [ 0.20855669, -1.20958693, -1.96922931,  0.23250855, -0.29338737],
       [ 0.99425658, -0.78739753, -0.72412312,  0.38440465, -0.63963954],
       [ 1.19792289,  0.60487797,  0.84599383, -0.15387342,  0.69526519],
       [-0.48291733,  1.39702321,  0.46492807, -0.14920309, -0.14367675]])

### randint
Retorna valores aletórios interios a partir de `low` (inclusive) até `high` (exclusivo).

In [19]:
np.random.randint(1,100)

72

In [20]:
np.random.randint(1,100,10)

array([22, 15, 12, 48, 38, 83, 76, 35, 15, 45])

=========================================================================================

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([ 1, 16, 11, 30, 22,  9, 33, 15, 23, 39])

## Reshape

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max min argmax e argmin


In [25]:
ranarr

array([ 1, 16, 11, 30, 22,  9, 33, 15, 23, 39])

In [26]:
ranarr.max()

39

In [27]:
ranarr.argmax()

9

In [28]:
ranarr.min()

1

In [29]:
ranarr.argmin()

0

## Shape

In [30]:
arr.shape

(25,)

In [31]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [35]:
arr.dtype

dtype('int32')

# NumPy Operations

## Aritmética

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [12]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# NumPy Indexação e seleção

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Obtendo elementos do array

In [16]:
arr[8]

8

In [17]:
#Slice
arr[1:5]

array([1, 2, 3, 4])

In [24]:
arr[5:-1]

array([5, 6, 7, 8, 9])

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [52]:
# Reiniciando array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Observe que o valor também é alterado no array original!

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Vamos agora copiar os dados originais para criar, de fato, um novo array. Assim poderemos alterá-lo sem impactar no array original

In [56]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Trabalhando com matrizes

In [25]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[1]

array([20, 25, 30])

In [59]:
arr_2d[1][0]

20

In [60]:
arr_2d[1,0]

20

In [30]:
# 2D Slicing
arr_2d[:2] # :2 exclusivo - 1: inclusive

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
# 2D Slicing
arr_2d[:,:2] # :2 exclusivo - 1: inclusive

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [61]:
# 2D Slicing
arr_2d[:2,1:] # :2 exclusivo - 1: inclusive

array([[10, 15],
       [25, 30]])

In [62]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [63]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Indexação avançada

In [64]:
arr2d = np.zeros((10,10))

In [65]:
arr_length = arr2d.shape[1]
arr_length

10

In [66]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [67]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [68]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Seleção

In [69]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])