## Vetor

In [1]:
# Vetor possui 1 dimensão e 1 tipo de dado.

vetor1 <- c(1:20)
vetor1
length(vetor1)
mode(vetor1)
class(vetor1)
typeof(vetor1)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1] 20

[1] "numeric"

[1] "integer"

[1] "integer"

## Matriz

In [2]:
# Matriz possui 2 dimensões e 1 tipo de dado.

matriz1 <- matrix(1:20, nrow=2)
matriz1
length(matriz1)
mode(matriz1)
class(matriz1)
typeof(matriz1)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    3    5    7     9   11   13   15   17   19   
[2,] 2    4    6    8    10   12   14   16   18   20

[1] 20

[1] "numeric"

[1] "matrix"

[1] "integer"

## Array

In [3]:
# Array: possui 2 ou mais dimensões e 1 tipo de dado.

array1 <- array(1:5, dim = c(3,3,3))
array1
length(array1)
mode(array1)
class(array1)
typeof(array1)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    2
[2,]    2    5    3
[3,]    3    1    4

, , 2

     [,1] [,2] [,3]
[1,]    5    3    1
[2,]    1    4    2
[3,]    2    5    3

, , 3

     [,1] [,2] [,3]
[1,]    4    2    5
[2,]    5    3    1
[3,]    1    4    2

[1] 27

[1] "numeric"

[1] "array"

[1] "integer"

## Data frame

In [6]:
# Data Frame: Dados de diferentes tipos. É uma Matriz com diferentes tipos de dados.

View(iris)
length(iris)
mode(iris)
class(iris)
typeof(iris)

ERROR: Error in View(iris): 'View()' not yet supported in the Jupyter R kernel


## Lista

In [8]:
# Listas: coleção de diferentes objetos. Diferentes tipos de dados são possíveis e comuns.

lista1 <- list(a = matriz1, b = vetor1)
lista1
length(lista1)
mode(lista1)
class(lista1)
typeof(lista1)

$a
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    3    5    7    9   11   13   15   17    19
[2,]    2    4    6    8   10   12   14   16   18    20

$b
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[1] 2

[1] "list"

[1] "list"

[1] "list"

## Função

In [12]:
# Funções também são vistas como objetos em R.

func1 <- function(x)
{
    var1 <- x * x
    return(var1)
}

func1(5)
class(func1)

[1] 25

[1] "function"

## Removendo Objetos.

In [13]:
objects()
rm(array1, func1)
objects()

[1] "array1"  "func1"   "lista1"  "matriz1" "vetor1"

[1] "lista1"  "matriz1" "vetor1"