# Use list() para criar listas

# Lista de strings.

In [5]:
lista_caracter_1 = list('A','B','C')
lista_caracter_1

lista_caracter_2 = list(c("A","A"), 'B','C')
lista_caracter_2

lista_caracter_3 = list(matrix(c("A","A","A","A"), nrow = 2),'B','C')
lista_caracter_3

[[1]]
[1] "A"

[[2]]
[1] "B"

[[3]]
[1] "C"

[[1]]
[1] "A" "A"

[[2]]
[1] "B"

[[3]]
[1] "C"

[[1]]
     [,1] [,2]
[1,] "A"  "A" 
[2,] "A"  "A" 

[[2]]
[1] "B"

[[3]]
[1] "C"

# Lista de números inteiros.

In [6]:
lista_inteiros = list(2,3,4)
lista_inteiros

[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 4

# Lista de floats.

In [7]:
lista_floats = list(2.0,3.0,4.0)
lista_floats

[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 4

# Lista de números complexos.

In [8]:
lista_complexos = list(5.2+3i, 2.4+8i)
lista_complexos

[[1]]
[1] 5.2+3i

[[2]]
[1] 2.4+8i

# Lista de valores lógicos.

In [9]:
lista_logicos = list(TRUE, FALSE, TRUE)
lista_logicos

[[1]]
[1] TRUE

[[2]]
[1] FALSE

[[3]]
[1] TRUE

# lista Composta.

In [11]:
lista_composta = list("B", 2, TRUE)
lista_composta

[[1]]
[1] "B"

[[2]]
[1] 2

[[3]]
[1] TRUE

In [13]:
lista_1 <- list(1:10, c("Zico","Ronaldo","Garrincha"), rnorm(10))
lista_1

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
[1] "Zico"      "Ronaldo"   "Garrincha"

[[3]]
 [1] -0.1349462  0.8362618 -0.5254162  0.4963972  0.4353512 -0.4549800
 [7]  0.2754026  1.0195782  0.8023078  0.8712733

# Slicing (Fatiamento) da lista.

In [16]:
lista_1[1]
lista_1[2]
lista_1[2][1]
lista_1[2][1] = "Mônica"
lista_1

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[1]]
[1] "Zico"      "Ronaldo"   "Garrincha"

[[1]]
[1] "Zico"      "Ronaldo"   "Garrincha"

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
[1] "Mônica"

[[3]]
 [1] -0.1349462  0.8362618 -0.5254162  0.4963972  0.4353512 -0.4549800
 [7]  0.2754026  1.0195782  0.8023078  0.8712733

# Para nomear os elementos - Listas Nomeadas.

In [18]:
names(lista_1) <- c("Inteiros","Caracteres","Numéricos")
lista_1

$Inteiros
 [1]  1  2  3  4  5  6  7  8  9 10

$Caracteres
[1] "Mônica"

$Numéricos
 [1] -0.1349462  0.8362618 -0.5254162  0.4963972  0.4353512 -0.4549800
 [7]  0.2754026  1.0195782  0.8023078  0.8712733

In [19]:
vec_num <- 1:4
vec_char <- c("A","B","C","D")

lista_2 <- list(Numeros = vec_num, Letras = vec_char)
lista_2

$Numeros
[1] 1 2 3 4

$Letras
[1] "A" "B" "C" "D"

# Nomear os elementos diretamente.

In [20]:
lista_2 <- list(elemento_1 = 3:5, elemento_2 = c(7.2, 3.5))
lista_2

$elemento_1
[1] 3 4 5

$elemento_2
[1] 7.2 3.5

# Trabalhando os elementos específicos da lista.

In [26]:
names(lista_1) <- c("Inteiros","Caracteres","Numéricos")
lista_1

$Inteiros
 [1]  1  2  3  4  5  6  7  8  9 10

$Caracteres
[1] "Mônica"

$Numéricos
 [1] -0.1349462  0.8362618 -0.5254162  0.4963972  0.4353512 -0.4549800
 [7]  0.2754026  1.0195782  0.8023078  0.8712733

In [30]:
lista_1$Caracteres
length(lista_1$Inteiros)
lista_1$Inteiros

[1] "Mônica"

[1] 10

[1]  1  2  3  4  5  6  7  8  9 10

# Verificando o comprimento da lista.

In [31]:
length(lista_1)

[1] 3

# Podemos extrair um elemento específico de dentro de cada nível da lista.

In [37]:
lista_1$Caracteres[1]

[1] "Mônica"

# Mode dos elementos.

In [38]:
mode(lista_1$Numéricos)
mode(lista_1$Caracteres)

[1] "numeric"

[1] "character"

# Combinando 2 listas.

In [39]:
lista_3 <- c(lista_1,lista_2)
lista_3

$Inteiros
 [1]  1  2  3  4  5  6  7  8  9 10

$Caracteres
[1] "Mônica"

$Numéricos
 [1] -0.1349462  0.8362618 -0.5254162  0.4963972  0.4353512 -0.4549800
 [7]  0.2754026  1.0195782  0.8023078  0.8712733

$elemento_1
[1] 3 4 5

$elemento_2
[1] 7.2 3.5

# Transformando um vetor em lista.

In [41]:
v = c(1:3)
v

l = as.list(v)
l

[1] 1 2 3

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

# Unindo 2 elementos em uma lista.

In [43]:
mat = matrix(1:4, nrow = 2)
mat

vec = c(1:9)
vec

lst  = list(mat, vec)
lst

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] 1 2 3 4 5 6 7 8 9

[[1]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[2]]
[1] 1 2 3 4 5 6 7 8 9

In [17]:
?rnorm

Normal                  package:stats                  R Documentation

_T_h_e _N_o_r_m_a_l _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Density, distribution function, quantile function and random
     generation for the normal distribution with mean equal to 'mean'
     and standard deviation equal to 'sd'.

_U_s_a_g_e:

     dnorm(x, mean = 0, sd = 1, log = FALSE)
     pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     rnorm(n, mean = 0, sd = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If 'length(n) > 1', the length is
          taken to be the number required.

    mean: vector of means.

      sd: vector of standard deviations.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x]
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If 'mean' or 'sd' are not specified they assume the default values
     of '0' and '1', respectively.

     The normal distribution has density

            f(x) = 1/(sqrt(2 pi) sigma) e^-((x - mu)^2/(2 sigma^2))     
     
     where mu is the mean of the distribution and sigma the standard
     deviation.

_V_a_l_u_e:

     'dnorm' gives the density, 'pnorm' gives the distribution
     function, 'qnorm' gives the quantile function, and 'rnorm'
     generates random deviates.

     The length of the result is determined by 'n' for 'rnorm', and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than 'n' are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

     For 'sd = 0' this gives the limit as 'sd' decreases to 0, a point
     mass at 'mu'.  'sd < 0' is an error and returns 'NaN'.

_S_o_u_r_c_e:

     For 'pnorm', based on

     Cody, W. D. (1993) Algorithm 715: SPECFUN - A portable FORTRAN
     package of special function routines and test drivers.  _ACM
     Transactions on Mathematical Software_ *19*, 22-32.

     For 'qnorm', the code is a C translation of

     Wichura, M. J. (1988) Algorithm AS 241: The percentage points of
     the normal distribution.  _Applied Statistics_, *37*, 477-484.

     which provides precise results up to about 16 digits.

     For 'rnorm', see RNG for how to select the algorithm and for
     references to the supplied methods.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Johnson, N. L., Kotz, S. and Balakrishnan, N. (1995) _Continuous
     Univariate Distributions_, volume 1, chapter 13.  Wiley, New York.

_S_e_e _A_l_s_o:

     Distributions for other standard distributions, including 'dlnorm'
     for the _Log_normal distribution.

_E_x_a_m_p_l_e_s:

     require(graphics)
     
     dnorm(0) == 1/sqrt(2*pi)
     dnorm(1) == exp(-1/2)/sqrt(2*pi)
     dnorm(1) == 1/sqrt(2*pi*exp(1))
     
     ## Using "log = TRUE" for an extended range :
     par(mfrow = c(2,1))
     plot(function(x) dnorm(x, log = TRUE), -60, 50,
          main = "log { Normal density }")
     curve(log(dnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("dnorm(x, log=TRUE)", adj = 0)
     mtext("log(dnorm(x))", col = "red", adj = 1)
     
     plot(function(x) pnorm(x, log.p = TRUE), -50, 10,
          main = "log { Normal Cumulative }")
     curve(log(pnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("pnorm(x, log=TRUE)", adj = 0)
     mtext("log(pnorm(x))", col = "red", adj = 1)
     
     ## if you want the so-called 'error function'
     erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1
     ## (see Abramowitz and Stegun 29.2.29)
     ## and the so-called 'complementary error function'
     erfc <- 