In [1]:
# unlist()
# Produz um vetor com os elementos da lista
?unlist

lst1 <- list(6, "b", 15)
lst1
class(lst1)

unlist(lst1)
vec1 <- unlist(lst1)
class(vec1)
vec1

lst2 <- list(v1 = 6, v2 = list(381, 2190), v3 = c(30, 217))
lst2

unlist(lst2)

mean(unlist(lst2))
round(mean(unlist(lst2)))

[[1]]
[1] 6

[[2]]
[1] "b"

[[3]]
[1] 15

[1] "list"

[1] "6"  "b"  "15"

[1] "character"

[1] "6"  "b"  "15"

$v1
[1] 6

$v2
$v2[[1]]
[1] 381

$v2[[2]]
[1] 2190


$v3
[1]  30 217

v1  v21  v22  v31  v32 
   6  381 2190   30  217

[1] 564.8

[1] 565

unlist                  package:base                   R Documentation

_F_l_a_t_t_e_n _L_i_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     Given a list structure 'x', 'unlist' simplifies it to produce a
     vector which contains all the atomic components which occur in
     'x'.

_U_s_a_g_e:

     unlist(x, recursive = TRUE, use.names = TRUE)
     
_A_r_g_u_m_e_n_t_s:

       x: an R object, typically a list or vector.

recursive: logical.  Should unlisting be applied to list components of
          'x'?

use.names: logical.  Should names be preserved?

_D_e_t_a_i_l_s:

     'unlist' is generic: you can write methods to handle specific
     classes of objects, see InternalMethods, and note, e.g., 'relist'
     with the 'unlist' method for 'relistable' objects.

     If 'recursive = FALSE', the function will not recurse beyond the
     first level items in 'x'.

     Factors are treated specially.  If all non-list elements of 'x'
     are factors (or ordered factors) then the result will be a factor
     with levels the union of the level sets of the elements, in the
     order the levels occur in the level sets of the elements (which
     means that if all the elements have the same level set, that is
     the level set of the result).

     'x' can be an atomic vector, but then 'unlist' does nothing
     useful, not even drop names.

     By default, 'unlist' tries to retain the naming information
     present in 'x'.  If 'use.names = FALSE' all naming information is
     dropped.

     Where possible the list elements are coerced to a common mode
     during the unlisting, and so the result often ends up as a
     character vector.  Vectors will be coerced to the highest type of
     the components in the hierarchy NULL < raw < logical < integer <
     double < complex < character < list < expression: pairlists are
     treated as lists.

     A list is a (generic) vector, and the simplified vector might
     still be a list (and might be unchanged).  Non-vector elements of
     the list (for example language elements such as names, formulas
     and calls) are not coerced, and so a list containing one or more
     of these remains a list.  (The effect of unlisting an 'lm' fit is
     a list which has individual residuals as components.)  Note that
     'unlist(x)' now returns 'x' unchanged also for non-vector 'x',
     instead of signalling an error in that case.

_V_a_l_u_e:

     'NULL' or an expression or a vector of an appropriate mode to hold
     the list components.

     The output type is determined from the highest type of the
     components in the hierarchy NULL < raw < logical < integer <
     double < complex < character < list < expression, after coercion
     of pairlists to lists.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'c', 'as.list', 'relist'.

_E_x_a_m_p_l_e_s:

     unlist(options())
     unlist(options(), use.names = FALSE)
     
     l.ex <- list(a = list(1:5, LETTERS[1:5]), b = "Z", c = NA)
     unlist(l.ex, recursive = FALSE)
     unlist(l.ex, recursive = TRUE)
     
     l1 <- list(a = "a", b = 2, c = pi+2i)
     unlist(l1) # a character vector
     l2 <- list(a = "a", b = as.name("b"), c = pi+2i)
     unlist(l2) # remains a list
     
     ll <- list(as.name("sinc"), quote( a + b ), 1:10, letters, expression(1+x))
     utils::str(ll)
     for(x in ll)
       stopifnot(identical(x, unlist(x)))

In [2]:
# do.call()
# Executa uma função em um objeto
# *** ATENÇÃO ***
# As funções da família apply aplicam uma função a cada elemento de um objeto (substitui um loop)
# A função do.call aplica uma função ao objeto inteiro e não a cada elemento individualmente
?do.call

data <- list()
N <- 100

for (n in 1:N) {
  data[[n]] = data.frame(index = n, char = sample(letters, 1), z = rnorm(1))
}

head(data)

do.call(rbind, data)
class(do.call(rbind, data))

[[1]]
  index char       z
1     1    e 0.28668

[[2]]
  index char         z
1     2    w -1.357628

[[3]]
  index char        z
1     3    c 1.403252

[[4]]
  index char        z
1     4    m 0.513545

[[5]]
  index char         z
1     5    l 0.3698234

[[6]]
  index char         z
1     6    n 0.4980261

index char z           
1    1    e     0.286680012
2    2    w    -1.357628248
3    3    c     1.403251704
4    4    m     0.513545011
5    5    l     0.369823407
6    6    n     0.498026115
7    7    w    -1.433881710
8    8    y    -0.335301228
9    9    g    -0.284426779
10  10    a     0.935044722
11  11    z    -1.141099417
12  12    e    -1.215575534
13  13    e     0.864735992
14  14    k     1.357398005
15  15    c     0.781456349
16  16    b     0.432199601
17  17    y    -0.415277309
18  18    v     0.271095118
19  19    k     1.151650754
20  20    c    -0.275310483
21  21    m    -0.903084224
22  22    g     0.632576753
23  23    s     0.210645506
24  24    h    -1.975567159
25  25    l    -1.481328067
26  26    q     0.016941827
27  27    r     0.002009241
28  28    c    -0.520790732
29  29    t     0.723187631
30  30    w     0.307756227
... ...   ...  ...         
71   71   j     0.849270982
72   72   w    -1.302980717
73   73   c     0.407339356
74   74   u    -0.150523122
75   75   n    -1.234305443
76   76   r     0.907856282
77   77   w    -0.142591291
78   78   s    -0.076680025
79   79   q     2.094947355
80   80   q    -0.637663628
81   81   x    -0.766053887
82   82   x     0.003841642
83   83   h     0.540893557
84   84   n     0.292703438
85   85   r     0.797644993
86   86   m     0.458327725
87   87   r     2.272134221
88   88   g    -0.830708026
89   89   b     1.400391058
90   90   d    -1.620196496
91   91   p    -0.905676503
92   92   c    -0.804874770
93   93   d     0.447224305
94   94   f     1.211050118
95   95   d    -0.608664884
96   96   o    -0.421961691
97   97   g    -1.101392996
98   98   x    -1.221179898
99   99   j     0.902927583
100 100   k    -0.153534717

[1] "data.frame"

do.call                  package:base                  R Documentation

_E_x_e_c_u_t_e _a _F_u_n_c_t_i_o_n _C_a_l_l

_D_e_s_c_r_i_p_t_i_o_n:

     'do.call' constructs and executes a function call from a name or a
     function and a list of arguments to be passed to it.

_U_s_a_g_e:

     do.call(what, args, quote = FALSE, envir = parent.frame())
     
_A_r_g_u_m_e_n_t_s:

    what: either a function or a non-empty character string naming the
          function to be called.

    args: a _list_ of arguments to the function call.  The 'names'
          attribute of 'args' gives the argument names.

   quote: a logical value indicating whether to quote the arguments.

   envir: an environment within which to evaluate the call.  This will
          be most useful if 'what' is a character string and the
          arguments are symbols or quoted expressions.

_D_e_t_a_i_l_s:

     If 'quote' is 'FALSE', the default, then the arguments are
     evaluated (in the calling environment, not in 'envir').  If
     'quote' is 'TRUE' then each argument is quoted (see 'quote') so
     that the effect of argument evaluation is to remove the quotes -
     leaving the original arguments unevaluated when the call is
     constructed.

     The behavior of some functions, such as 'substitute', will not be
     the same for functions evaluated using 'do.call' as if they were
     evaluated from the interpreter.  The precise semantics are
     currently undefined and subject to change.

_V_a_l_u_e:

     The result of the (evaluated) function call.

_W_a_r_n_i_n_g:

     This should not be used to attempt to evade restrictions on the
     use of '.Internal' and other non-API calls.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'call' which creates an unevaluated call.

_E_x_a_m_p_l_e_s:

     do.call("complex", list(imag = 1:3))
     
     ## if we already have a list (e.g., a data frame)
     ## we need c() to add further arguments
     tmp <- expand.grid(letters[1:2], 1:3, c("+", "-"))
     do.call("paste", c(tmp, sep = ""))
     
     do.call(paste, list(as.name("A"), as.name("B")), quote = TRUE)
     
     ## examples of where objects will be found.
     A <- 2
     f <- function(x) print(x^2)
     env <- new.env()
     assign("A", 10, envir = env)
     assign("f", f, envir = env)
     f <- function(x) print(x)
     f(A)                                      # 2
     do.call("f", list(A))                     # 2
     do.call("f", list(A), envir = env)        # 4
     do.call(f, list(A), envir = env)          # 2
     do.call("f", list(quote(A)), envir = env) # 100
     do.call(f, list(quote(A)), envir = env)   # 10
     do.call("f", list(as.name("A")), envir = env) # 100
     
     eval(call("f", A))                      # 2
     eval(call("f", quote(A)))               # 2
     eval(call("f", A), envir = env)         # 4
     eval(call("f", quote(A)), envir = env)  # 100

In [3]:
# lapply() x do.call()
y <- list(1:3, 4:6, 7:9)
y

lapply(y, sum)
do.call(sum, y)

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

[[3]]
[1] 7 8 9

[[1]]
[1] 6

[[2]]
[1] 15

[[3]]
[1] 24

[1] 45

In [10]:
# O resultado da função lapply() pode ser obtido de outras formas
# Pacote plyr

#install.packages('plyr')
library(plyr)

y <- list(1:3, 4:6, 7:9)
y

ldply(y, sum)

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5 6

[[3]]
[1] 7 8 9

V1
1  6
2 15
3 24

In [5]:
# strsplit()
# Divide uma string ou vetor de caracteres

texto <- "Data Science Academy"
strsplit(texto, " ")

texto <- "Data Science Academy"
strsplit(texto, "")


dates <- c("1998-05-23", "2008-12-30", "2009-11-29")
temp  <- strsplit(dates, "-")
temp
class(temp)

[[1]]
[1] "Data"    "Science" "Academy"

[[1]]
 [1] "D" "a" "t" "a" " " "S" "c" "i" "e" "n" "c" "e" " " "A" "c" "a" "d" "e" "m"
[20] "y"

[[1]]
[1] "1998" "05"   "23"  

[[2]]
[1] "2008" "12"   "30"  

[[3]]
[1] "2009" "11"   "29"

[1] "list"

In [6]:
# Transforma a lista em matriz, fazendo antes um unlist()
matrix(unlist(temp), ncol = 3, byrow = TRUE)

Names <- c("Brin, Sergey", "Page, Larry",
           "Dorsey, Jack", "Glass, Noah",
            "Williams, Evan", "Stone, Biz")

temp <- strsplit(Names, ", ")
temp


frase <- "Muitas vezes temos que repetir algo diversas vezes e essas diversas vezes parecem algo estranho"
palavras <- strsplit(frase, " ")[[1]]
palavras
unique(tolower(palavras))

[,1] [,2] [,3]
[1,] 1998 05   23  
[2,] 2008 12   30  
[3,] 2009 11   29

[[1]]
[1] "Brin"   "Sergey"

[[2]]
[1] "Page"  "Larry"

[[3]]
[1] "Dorsey" "Jack"  

[[4]]
[1] "Glass" "Noah" 

[[5]]
[1] "Williams" "Evan"    

[[6]]
[1] "Stone" "Biz"

[1] "Muitas"   "vezes"    "temos"    "que"      "repetir"  "algo"    
 [7] "diversas" "vezes"    "e"        "essas"    "diversas" "vezes"   
[13] "parecem"  "algo"     "estranho"

[1] "muitas"   "vezes"    "temos"    "que"      "repetir"  "algo"    
 [7] "diversas" "e"        "essas"    "parecem"  "estranho"

In [7]:
# strplit() com dataframes
antes = data.frame(attr = c(1,30,4,6), tipo = c('pao_e_agua','pao_e_agua_2'))
antes
strsplit(as.character(antes$tipo),'_e_')


library(stringr)
str_split_fixed(antes$tipo, "_e_", 2)

attr tipo        
1  1   pao_e_agua  
2 30   pao_e_agua_2
3  4   pao_e_agua  
4  6   pao_e_agua_2

[[1]]
[1] "pao"  "agua"

[[2]]
[1] "pao"    "agua_2"

[[3]]
[1] "pao"  "agua"

[[4]]
[1] "pao"    "agua_2"

[,1] [,2]  
[1,] pao  agua  
[2,] pao  agua_2
[3,] pao  agua  
[4,] pao  agua_2

In [8]:
# Usando do.call()
antes = data.frame(attr = c(1,30,4,6), tipo = c('pao_e_agua','pao_e_agua_2'))
antes
depois <- strsplit(as.character(antes$tipo),'_e_')
depois
do.call(rbind, depois)

attr tipo        
1  1   pao_e_agua  
2 30   pao_e_agua_2
3  4   pao_e_agua  
4  6   pao_e_agua_2

[[1]]
[1] "pao"  "agua"

[[2]]
[1] "pao"    "agua_2"

[[3]]
[1] "pao"  "agua"

[[4]]
[1] "pao"    "agua_2"

[,1] [,2]  
[1,] pao  agua  
[2,] pao  agua_2
[3,] pao  agua  
[4,] pao  agua_2

In [11]:
# Usando dplyr e tidyr
#install.packages("dplyr")
#install.packages("tidyr")
library(dplyr)
library(tidyr)

antes <- data.frame(
  attr = c(1, 30 ,4 ,6 ), 
  tipo = c('pao_e_agua','pao_e_agua_2')
)

antes %>%
  separate(tipo, c("pao", "agua"), "_e_")


Attaching package: 'dplyr'

The following objects are masked from 'package:plyr':

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



attr pao agua  
1  1   pao agua  
2 30   pao agua_2
3  4   pao agua  
4  6   pao agua_2