In [1]:
# Exercício 1 - Pesquise pela função que permita listar todos os arquivos no 
# diretório de trabalho
list.files()

[1] "02-Big-Data-na-Pratica1.ipynb"           
 [2] "03-Fatores-e-Fatores-Ordenados.ipynb"    
 [3] "04-Fatores-Dataframes.ipynb"             
 [4] "05-Estruturas-de-Controle.ipynb"         
 [5] "06-Funcoes.ipynb"                        
 [6] "07-Familia-Apply.ipynb"                  
 [7] "08-Funcoes-Especiais.ipynb"              
 [8] "09-Pacotes-e-Instalacao-de-Pacotes.ipynb"
 [9] "10-Expressoes-Regulares.ipynb"           
[10] "11-Trabalhando-com-Datas.ipynb"          
[11] "12-Operadores-Atribuicao.ipynb"          
[12] "13-Exercicios.ipynb"                     
[13] "TemperaturasGlobais.rar"

In [2]:
# Exercício 2 - Crie um dataframe a partir de 3 vetores: um de caracteres, 
# um lógico e um de números
charac_vec <- c("A", "B", "C")
num_vec <- c(4.5, 3.9, 7.2)
logic_vec <- c(TRUE, TRUE, FALSE)
df1 <- data.frame(charac_vec, num_vec, logic_vec)
df1

charac_vec num_vec logic_vec
1 A          4.5      TRUE    
2 B          3.9      TRUE    
3 C          7.2     FALSE

In [3]:
# Exercício 3 - Considere o vetor abaixo. 
# Crie um loop que verifique se há números maiores que 10 e imprima o número 
# e uma mensagem no console.

# Criando um Vetor
vec1 <- c(12, 3, 4, 19, 34)
vec1

for (i in 1:length(vec1)){
  if (vec1[i] > 10) {
    print(vec1[i])
    print('Este elemento do vetor é maior que 10')
  } else  {
    print(vec1[i])
    print('Este elemento do vetor é menor que 10')
  } 
}

[1] 12  3  4 19 34

[1] 12
[1] "Este elemento do vetor é maior que 10"
[1] 3
[1] "Este elemento do vetor é menor que 10"
[1] 4
[1] "Este elemento do vetor é menor que 10"
[1] 19
[1] "Este elemento do vetor é maior que 10"
[1] 34
[1] "Este elemento do vetor é maior que 10"


In [4]:
# Exercício 4 - Conisdere a lista abaixo. Crie um loop que imprima no console 
# cada elemento da lista
lst2 <- list(2, 3, 5, 7, 11, 13)
lst2

for (i in 1:length(lst2)) {
  print(lst2[[i]])
}

[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 5

[[4]]
[1] 7

[[5]]
[1] 11

[[6]]
[1] 13

[1] 2
[1] 3
[1] 5
[1] 7
[1] 11
[1] 13


In [5]:
# Exercício 5 - Considere as duas matrizes abaixo. 
# Faça uma multiplicação element-wise e multiplicação normal entre as matrizes
# https://www.mathwarehouse.com/algebra/matrix/multiply-matrix.php
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
mat1
mat2 <- t(mat1)
mat2

# Multiplicação element-wise
mat3 <- mat1 * mat2	
mat3

# Multiplicação de matrizes 
# (multiplica primeira linha da mat1 com a primeira coluna de mat2
# Item [1,1] ==> (1 x 1) + (2 x 2) + (3 x 3) x (4 x 4) x (5 x 5) = 55
# Item [2,1] ==> (6 x 1) + (7 x 2) + (8 x 3) x (9 x 4) x (10 x 5) = 130
# Item [3,1] ==> (11 x 1) + (12) x 2) + (13 x 3) x (14 x 4) x (15 x 5) = 205
mat4 <- mat1 %*% mat2
mat4

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[,1] [,2] [,3] [,4] [,5]
[1,]   1   12   33   64  105 
[2,]  12   49   96  153  220 
[3,]  33   96  169  252  345 
[4,]  64  153  252  361  480 
[5,] 105  220  345  480  625

[,1] [,2] [,3] [,4] [,5]
[1,]  55  130   205  280  355
[2,] 130  330   530  730  930
[3,] 205  530   855 1180 1505
[4,] 280  730  1180 1630 2080
[5,] 355  930  1505 2080 2655

In [6]:
# Exercício 6 - Crie um vetor, matriz, lista e dataframe e faça a nomeação 
# de cada um dos objetos
vec1 <- c(12, 3, 4, 19, 34)
names(vec1) <- c('Col1', 'Col2', 'Col3', 'Col4', 'Col5')
vec1

mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
dimnames(mat1) = (list( c("Obs1", "Obs2", "Obs3", "Obs4", "Obs5"), c("Var1", "Var2", "Var3", "Var4", "Var5")))
mat1

lst1 <- list(2, 3, c(1, 2, 3))
names(lst1) <- c('dim1', 'dim2', 'dim3')
lst1

df1 <- data.frame(c("A", "B", "C"), c(4.5, 3.9, 7.2), c(TRUE, TRUE, FALSE))
colnames(df1) <- c('Caracteres', 'Float', 'Logico')
rownames(df1) <- c("Obs1", "Obs2", "Obs3")
df1

Col1 Col2 Col3 Col4 Col5 
  12    3    4   19   34

Var1 Var2 Var3 Var4 Var5
Obs1  1    2    3    4    5  
Obs2  6    7    8    9   10  
Obs3 11   12   13   14   15  
Obs4 16   17   18   19   20  
Obs5 21   22   23   24   25

$dim1
[1] 2

$dim2
[1] 3

$dim3
[1] 1 2 3

Caracteres Float Logico
Obs1 A          4.5    TRUE 
Obs2 B          3.9    TRUE 
Obs3 C          7.2   FALSE

In [7]:
# Exercício 7 - Considere a matriz abaixo. Atribua valores NA de forma aletória 
# para 50 elementos da matriz
# Dica: use a função sample()
mat2 <- matrix(1:90, 10)
mat2
?sample
mat2[sample(1:50, 10)] = NA
mat2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]  1   11   21   31   41   51   61   71   81  
 [2,]  2   12   22   32   42   52   62   72   82  
 [3,]  3   13   23   33   43   53   63   73   83  
 [4,]  4   14   24   34   44   54   64   74   84  
 [5,]  5   15   25   35   45   55   65   75   85  
 [6,]  6   16   26   36   46   56   66   76   86  
 [7,]  7   17   27   37   47   57   67   77   87  
 [8,]  8   18   28   38   48   58   68   78   88  
 [9,]  9   19   29   39   49   59   69   79   89  
[10,] 10   20   30   40   50   60   70   80   90

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]  1   11   21   NA   41   51   61   71   81  
 [2,]  2   12   NA   32   NA   52   62   72   82  
 [3,]  3   13   23   NA   43   53   63   73   83  
 [4,]  4   NA   24   34   44   54   64   74   84  
 [5,] NA   NA   25   35   45   55   65   75   85  
 [6,]  6   16   26   36   46   56   66   76   86  
 [7,]  7   17   27   37   47   57   67   77   87  
 [8,]  8   18   28   38   48   58   68   78   88  
 [9,]  9   19   NA   NA   49   59   69   79   89  
[10,] 10   20   30   NA   50   60   70   80   90

sample                  package:base                   R Documentation

_R_a_n_d_o_m _S_a_m_p_l_e_s _a_n_d _P_e_r_m_u_t_a_t_i_o_n_s

_D_e_s_c_r_i_p_t_i_o_n:

     'sample' takes a sample of the specified size from the elements of
     'x' using either with or without replacement.

_U_s_a_g_e:

     sample(x, size, replace = FALSE, prob = NULL)
     
     sample.int(n, size = n, replace = FALSE, prob = NULL,
                useHash = (!replace && is.null(prob) && size <= n/2 && n > 1e7))
     
_A_r_g_u_m_e_n_t_s:

       x: either a vector of one or more elements from which to choose,
          or a positive integer.  See 'Details.'

       n: a positive number, the number of items to choose from.  See
          'Details.'

    size: a non-negative integer giving the number of items to choose.

 replace: should sampling be with replacement?

    prob: a vector of probability weights for obtaining the elements of
          the vector being sampled.

 useHash: 'logical' indicating if the hash-version of the algorithm
          should be used.  Can only be used for 'replace = FALSE',
          'prob = NULL', and 'size <= n/2', and really should be used
          for large 'n', as 'useHash=FALSE' will use memory
          proportional to 'n'.

_D_e_t_a_i_l_s:

     If 'x' has length 1, is numeric (in the sense of 'is.numeric') and
     'x >= 1', sampling _via_ 'sample' takes place from '1:x'.  _Note_
     that this convenience feature may lead to undesired behaviour when
     'x' is of varying length in calls such as 'sample(x)'.  See the
     examples.

     Otherwise 'x' can be any R object for which 'length' and
     subsetting by integers make sense: S3 or S4 methods for these
     operations will be dispatched as appropriate.

     For 'sample' the default for 'size' is the number of items
     inferred from the first argument, so that 'sample(x)' generates a
     random permutation of the elements of 'x' (or '1:x').

     It is allowed to ask for 'size = 0' samples with 'n = 0' or a
     length-zero 'x', but otherwise 'n > 0' or positive 'length(x)' is
     required.

     Non-integer positive numerical values of 'n' or 'x' will be
     truncated to the next smallest integer, which has to be no larger
     than '.Machine$integer.max'.

     The optional 'prob' argument can be used to give a vector of
     weights for obtaining the elements of the vector being sampled.
     They need not sum to one, but they should be non-negative and not
     all zero.  If 'replace' is true, Walker's alias method (Ripley,
     1987) is used when there are more than 200 reasonably probable
     values: this gives results incompatible with those from R < 2.2.0.

     If 'replace' is false, these probabilities are applied
     sequentially, that is the probability of choosing the next item is
     proportional to the weights amongst the remaining items.  The
     number of nonzero weights must be at least 'size' in this case.

     'sample.int' is a bare interface in which both 'n' and 'size' must
     be supplied as integers.

     Argument 'n' can be larger than the largest integer of type
     'integer', up to the largest representable integer in type
     'double'.  Only uniform sampling is supported.  Two random numbers
     are used to ensure uniform sampling of large integers.

_V_a_l_u_e:

     For 'sample' a vector of length 'size' with elements drawn from
     either 'x' or from the integers '1:x'.

     For 'sample.int', an integer vector of length 'size' with elements
     from '1:n', or a double vector if n >= 2^31.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Ripley, B. D. (1987) _Stochastic Simulation_. Wiley.

_S_e_e _A_l_s_o:

     'RNG' about random number generation.

     CRAN package 'sampling' for other methods of weighted sampling
     without re

In [8]:
# Exercício 8 - Para a matriz abaixo, calcule a soma por linha e por coluna
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
mat1
rowSums(mat1)
colSums(mat1)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[1]  15  40  65  90 115

[1] 55 60 65 70 75

In [9]:
# Exercício 9 - Para o vetor abaixo, ordene os valores em ordem crescente
a <- c(100, 10, 10000, 1000)
a
order(a)
a[order(a)]

[1]   100    10 10000  1000

[1] 2 1 4 3

[1]    10   100  1000 10000

In [10]:
# # Exercício 10 - Imprima no console todos os elementos da matriz abaixo 
# que forem maiores que 15
mat1 <- matrix(c(1:50), nrow = 5, ncol = 5, byrow = T)
mat1

for (i in mat1){
  if(i > 15){
    print(i)
  }
}

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[1] 16
[1] 21
[1] 17
[1] 22
[1] 18
[1] 23
[1] 19
[1] 24
[1] 20
[1] 25
